### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by dluc** [appcelerator/docker-grafana#22]
I tried to add a dashboard, using a JSON exported from Grafana, but run.sh fails to create it with this error:

```
[{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]
```

For datasources I'm writing directly to the sqlite db, but I like the approach of going through the API, I just couldn't find examples.

Could you provide a couple of samples, one for dashboard and one for a datasource?

Thanks!

**Comment by ndegory** [comment]
@dluc , you may have to modify the json you exported from Grafana, I had to do it to adjust to the format Grafana is expecting for the import.
You should have something like this:
```
{
  "Dashboard":
  {
    "id": null,
    "title": "Title of the dashboard",
    "tags": [],
    "style": "dark",
    "timezone": "browser",
    "editable": true,
    "hideControls": false,
    "sharedCrosshair": false,
    "rows": [
    ]
 }
}
```

For a datasource, here's an exemple for influxdb:
```
{
    "name":"telegraf",
    "type":"influxdb",
    "url":"http://localhost:8086",
    "access":"proxy",
    "isDefault":true,
    "database":"telegraf",
    "user":"admin",
    "password":"pwd"
}
```

**Comment by dluc** [comment]
Thank you!
BTW, here's an example for Prometheus data source if anyone stumbles on this:

```
{
  "name": "myprometheus",
  "type": "prometheus",
  "url": "http://prometheus-ip:9090",
  "access": "proxy",
  "isDefault": true
}
```
