### ISSUE TITLE
How to run docker with grafana4.6.3 successfully

### ISSUE THREAD

**Issue by ZeroMagic** [appcelerator/docker-grafana#25]
Now, I have a problem.
```
docker run -d -p 3000:3000 \
-v /tmp/config:/etc/extra-config/grafana:ro \
-v /tmp/grafana.ini:/etc/grafana/grafana.ini \
grafana/grafana:4.6.3
```
I put the config files about datasource and dashboards into /tmp/config. 
And set the "grafana.ini" as below.
```
[dashboards.json]
enabled = true
path = /etc/extra-config/grafana/dashboard.js
```
But the container's state is "Exited (1)".

Maybe my usage is wrong.
What is the correct usage?

**Comment by ZeroMagic** [comment]
@ndegory could you help me ?

**Comment by ndegory** [comment]
@ZeroMagic you shouldn't have to mount the grafana.ini file, as long as you have your datasource and dashboard files as /etc/extra-config/grafana/config-datasource*.js and etc/extra-config/grafana/config-dashboard*.js (or .tpl go templates), it will be loaded by Grafana.
If you have to modify the configuration, please mount it as /etc/base-config/grafana/defaults.ini.

**Comment by ZeroMagic** [comment]
@ndegory It means that in this case, I don't need to modify the configuration. I just need to mount the extra-config.
Then I use the below command
```
docker run -d -p 3000:3000 \
-v /tmp/config:/etc/extra-config/grafana:ro \
grafana/grafana:4.6.3
```
The container is running successfully.
But Grafana doesn't load my datasources and dashboards.

**Comment by ZeroMagic** [comment]
@ndegory Thanks for your help.
Just now, my file's format is false. Now it works well.
